### ISSUE TITLE
PonyDebugger server not able to install

### ISSUE THREAD

**Issue by grevolution** [square/PonyDebugger#109]
Hi, 

I am trying to install ponydebugger sever, but its giving me a weird error every time. i have Xcode5 installed and command line tools are also installed. Following is the command line trace that I am getting always. 

```
grevolution:~ shanulhaq$ curl -sk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py |   python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
New python executable in /Users/shanulhaq/Library/PonyDebugger/bin/python
Installing setuptools.......
  Complete output from command /Users/shanulhaq/Lib...yDebugger/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" --always-copy -U setuptools:
  Searching for setuptools
Reading https://pypi.python.org/simple/setuptools/
Reading http://peak.telecommunity.com/snapshots/
error: Connection reset by peer
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 944, in main
  File "<stdin>", line 1054, in create_environment
  File "<stdin>", line 600, in install_setuptools
  File "<stdin>", line 572, in _install_req
  File "<stdin>", line 1022, in call_subprocess
OSError: Command /Users/shanulhaq/Lib...yDebugger/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])






" --always-copy -U setuptools failed with error code 1
```

**Comment by dms90** [comment]
@grevolution how do you fix it?
