### ISSUE TITLE
Cannot install Script

### ISSUE THREAD

**Issue by jadar** [square/PonyDebugger#153]
I'm running OSX 10.10, and I can't seem to install the script. I have the Python 2.7.6 installed. I tried installing pybonjour manually but that didn't help.

```
|⇒  curl -s https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | \
  python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
New python executable in /Users/jacob/Library/PonyDebugger/bin/python2.7
Also creating executable in /Users/jacob/Library/PonyDebugger/bin/python
Installing setuptools.............................done.
Installing pip............................done.
Obtaining ponydebugger from git+https://github.com/square/PonyDebugger.git#egg=ponydebugger
  Cloning https://github.com/square/PonyDebugger.git to ./Library/PonyDebugger/src/ponydebugger
Collecting tornado (from ponydebugger)
  Using cached tornado-4.1.tar.gz
Collecting pybonjour (from ponydebugger)
  Could not find a version that satisfies the requirement pybonjour (from ponydebugger) (from versions: )
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external pybonjour to allow).
  No matching distribution found for pybonjour (from ponydebugger)
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 946, in main
  File "<stdin>", line 1794, in after_install
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/jacob/Library/PonyDebugger/bin/pip', 'install', '-U', '-e', 'git+https://github.com/square/PonyDebugger.git#egg=ponydebugger']' returned non-zero exit status 1
```

**Comment by klivin** [comment]
Got this same error

**Comment by hamdullahshah** [comment]
You have to add '--allow-external', and  '--allow-unverified' to pybonjour to install.

here is a shortcut.. 
download [ponyd bootstrap file] (https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py)
replace the text in file with [this text] (http://pastebin.com/CStmGCKM)

then in terminal run 
`python bootstrap-ponyd.py --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger`

After that most probably you will face another issue of 'DistributionNotFound: certifi' on which i spent 5 hours :p
here is the solution for that...
[download setup tools] (https://bitbucket.org/pypa/setuptools/get/default.tar.gz#egg=setuptools-dev) and extract

you will find a file inside folder 'setup.py' then run 
`python setup.py install --prefix=~/Library/PonyDebugger/`

after that run  
`ponyd update-devtools`

and then good to go :dancer:

**Comment by nleachCHS** [comment]
Thanks @hamdullahshah your fix worked for me!

**Comment by stephenmerendino** [comment]
@hamdullahshah Fixed the problem for me as well, thanks!

**Comment by buithuyen** [comment]
I'm having a problem
```python
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'setup_requires'
  warnings.warn(msg)
running install
Checking .pth file support in /Users/thuyenbv/Library/PonyDebugger//lib/python2.7/site-packages/
/usr/bin/python -E -c pass
TEST FAILED: /Users/thuyenbv/Library/PonyDebugger//lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/thuyenbv/Library/PonyDebugger//lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations
```
How should I do to fix them

**Comment by hamdullahshah** [comment]
i think the problem is there are two "/" in the path after "PonyDebugger"

`Checking .pth file support in /Users/thuyenbv/Library/PonyDebugger//lib/python2.7/site-packages/
/usr/bin/python -E -c pass
TEST FAILED: /Users/thuyenbv/Library/PonyDebugger//lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH
`

**Comment by buithuyen** [comment]
I have tried again. But I have still problem
```python
ThuyenBV:pypa-setuptools-e517fced669d ThuyenBV$ python setup.py install --prefix=~/Library/PonyDebugger
running install
Checking .pth file support in /Users/ThuyenBV/Library/PonyDebugger/lib/python2.7/site-packages/
/usr/bin/python -E -c pass
TEST FAILED: /Users/ThuyenBV/Library/PonyDebugger/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/ThuyenBV/Library/PonyDebugger/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
```
<img width="1266" alt="screen shot 2016-01-14 at 4 44 01 pm" src="https://cloud.githubusercontent.com/assets/5087522/12320969/341fd7d6-bade-11e5-8b6d-2aadf5c8fd5d.png">

Do I have any mistakes or missing?
