### ISSUE TITLE
Failure trying to update to latest devtools version

### ISSUE THREAD

**Issue by jeanregisser** [square/PonyDebugger#61]
Hi,

I noticed the Chrome Dev Tools project stopped updating `devtools_frontend.zip` on their continuous build server.
See https://code.google.com/p/chromium/issues/detail?id=160561

They now advise people to use the blink repository directly and play with the Dev Tools files in `WebKit/Source/WebCore/inspector`. 

PonyDebugger could clone the repository instead of downloading the zip, but I'm afraid it's way too big (over 4 Gigs!).
Another way would be to package and host a zip of `WebKit/Source/WebCore/inspector` regularly ourself.

So I wonder what would be best for the PonyDebugger project.
What's your take on this @ryanolsonk @mikelikespie @wlue?

As a reference, here's the current output if you try to get the latest devtools with ponyd:

```
 $ ponyd update-devtools --latest
Downloading http://storage.googleapis.com/chromium-browser-continuous/Mac/192797/devtools_frontend.zip
Traceback (most recent call last):
  File "/Users/jean/.virtualenvs/ponydenv/bin/ponyd", line 8, in <module>
    load_entry_point('ponyd==1.0', 'console_scripts', 'ponyd')()
  File "/Users/jean/Developments/my-PonyDebugger/ponyd/argbase.py", line 149, in main
    args.command(args)
  File "/Users/jean/Developments/my-PonyDebugger/ponyd/argbase.py", line 128, in run_command
    return instance()
  File "/Users/jean/Developments/my-PonyDebugger/ponyd/downloader.py", line 36, in __call__
    tools_stream = StringIO(urllib2.urlopen(tools_url).read())
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by stephanepechard** [comment]
+1
