### ISSUE TITLE
can't excute the command

### ISSUE THREAD

**Issue by zn88358800** [square/PonyDebugger#68]
zhangmatoMacBook-Pro:Desktop zn88358800$ curl -sk https://cloud.github.com/downloads/square/PonyDebugger/bootstrap-ponyd.py | python - --ponyd-symlink=/usr/local/bin/ponyd ~/Library/PonyDebugger
New python executable in /Users/zn88358800/Library/PonyDebugger/bin/python
Installing setuptools.....................
  Complete output from command /Users/zn88358800/Li...yDebugger/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" --always-copy -U setuptools:
  Traceback (most recent call last):
  File "<string>", line 279, in <module>
  File "<string>", line 240, in main
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/command/easy_install.py", line 1712, in main
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/command/easy_install.py", line 171, in finalize_options
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/package_index.py", line 161, in __init__
  File "/Users/zn88358800/Library/PonyDebugger/lib/python2.7/site-packages/setuptools-0.6c12dev_r88997-py2.7.egg/setuptools/ssl_support.py", line 239, in find_ca_bundle
NameError: global name 'pkg_resources' is not defined
----------------------------------------
...Installing setuptools...done.
Traceback (most recent call last):
  File "<stdin>", line 2462, in <module>
  File "<stdin>", line 944, in main
  File "<stdin>", line 1054, in create_environment
  File "<stdin>", line 600, in install_setuptools
  File "<stdin>", line 572, in _install_req
  File "<stdin>", line 1022, in call_subprocess
OSError: Command /Users/zn88358800/Li...yDebugger/bin/python -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" --always-copy -U setuptools failed with error code 1

how can i install it in a right way??

**Comment by davidapgar** [comment]
Going through and closing out old issues. If this is still something you believe to be an issues outside of the different python versions installed, please reopen. Thanks!
