### ISSUE TITLE
Getting "ERROR:root:Uncaught exception, closing connection" when browser loads gateway page

### ISSUE THREAD

**Issue by aneilbaboo** [square/PonyDebugger#89]
I'm on OS X 10.9 (Mavericks), using Python 2.7.  I did ```ponyd update-devtools```.

The ponyd server starts just fine:

```
$ ponyd serve
PonyGateway starting. Listening on 127.0.0.1:9000
```

I point my Chrome  31.0.1650.34 beta at 127.0.0.1:9000, and get this page:

```
PonyGateway
Connect a PonyDebugger client to ws://localhost:9000/device.

No Clients Connected
Status: Connecting to gateway...
```

The terminal shows this trace:
```
ERROR:root:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 204, in on_connection_close
    self.on_close()
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 177, in on_close
    self.app_state.removeLobby(self)
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 59, in removeLobby
    self.lobbies.remove(lobby)
KeyError: <ponyd.gateway.LobbyHandler object at 0x101fdb910>
ERROR:root:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 353, in _on_headers
    self.request_callback(self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 1204, in __call__
    handler._execute(transforms, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 82, in _execute
    self._abort()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 175, in _abort
    self.stream.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 180, in close
    self._run_callback(self._close_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 204, in on_connection_close
    self.on_close()
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 177, in on_close
    self.app_state.removeLobby(self)
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 59, in removeLobby
    self.lobbies.remove(lobby)
KeyError: <ponyd.gateway.LobbyHandler object at 0x101fdb910>
ERROR:root:Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 199, in _handle_events
    self._handle_read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 258, in _handle_read
    if self._read_from_buffer():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 325, in _read_from_buffer
    self._consume(loc + delimiter_len))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 353, in _on_headers
    self.request_callback(self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 1204, in __call__
    handler._execute(transforms, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 82, in _execute
    self._abort()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 175, in _abort
    self.stream.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 180, in close
    self._run_callback(self._close_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 204, in on_connection_close
    self.on_close()
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 177, in on_close
    self.app_state.removeLobby(self)
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 59, in removeLobby
    self.lobbies.remove(lobby)
KeyError: <ponyd.gateway.LobbyHandler object at 0x101fdb910>
ERROR:root:Exception in I/O handler for fd 20
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/ioloop.py", line 269, in start
    self._handlers[fd](fd, events)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 199, in _handle_events
    self._handle_read()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 258, in _handle_read
    if self._read_from_buffer():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 325, in _read_from_buffer
    self._consume(loc + delimiter_len))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/httpserver.py", line 353, in _on_headers
    self.request_callback(self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/web.py", line 1204, in __call__
    handler._execute(transforms, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 82, in _execute
    self._abort()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 175, in _abort
    self.stream.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 180, in close
    self._run_callback(self._close_callback)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/iostream.py", line 230, in _run_callback
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/stack_context.py", line 173, in wrapped
    callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tornado/websocket.py", line 204, in on_connection_close
    self.on_close()
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 177, in on_close
    self.app_state.removeLobby(self)
  File "/Users/aneil/Library/PonyDebugger/src/ponydebugger/ponyd/gateway.py", line 59, in removeLobby
    self.lobbies.remove(lobby)
KeyError: <ponyd.gateway.LobbyHandler object at 0x101fdb910>

```

**Comment by davidapgar** [comment]
We're going through closing out old issues. If this is still something that reproduces, please reopen this. Thanks!
